import Link from 'next/link';

export default function About() {
  return (
    <div className="bg-gray-800 text-white max-w-screen min-h-screen space-y-3">
      <ul className="p-10 space-y-10">
        <h1 className="lg:text-5xl text-3xl font-serif">
          The Auschwitz Project was made possible by applied generative
          artificial intelligence. Here's what that means:
        </h1>
        <li className="lg:text-lg text-md list-disc">
          Generative AI is a type of machine learning that can generate new
          content based on a given input. For example, a generative AI model can
          be trained to write a new sentence based on a given prompt. The model
          will then generate a new sentence that is similar to the prompt.
        </li>
        <li className="lg:text-lg text-md list-disc">
          Generative AI models are trained on large amounts of data. The more
          data a model is trained on, the better it will be able to generate new
          content. For example, a model trained on the entire works of
          Shakespeare will be able to generate new sentences that are similar to
          Shakespeare's writing.
        </li>
        <li className="lg:text-lg text-md list-disc">
          Applied generative AI is a type of generative AI that is used to solve
          real-world problems. For example, a generative AI model can be trained
          to write a new sentence based on a given prompt. The model will then
          generate a new sentence that is similar to the prompt.
        </li>
        <li className="lg:text-lg text-md list-disc">
          The Auschwitz Project uses applied generative AI to generate new
          content based on the primary accounts of Auschwitz. The model is
          trained on the provided corpus of primary accounts of Auschwitz. The
          model is then used to generate new content that is mathematically
          similar to the primary accounts of Auschwitz to provide an accurate,
          360° picture of the commandant's testimony coupled with primary
          accounts to back it up and sources. The model was ordered not to use
          sources that it was not trained on (primary testimony), and most of
          its answers are verifiably accurate.
        </li>
        <li className="lg:text-lg text-md list-disc">
          This is powered by GPT-4 API from OpenAI. GPT-4 is a large language
          model that is trained on a variety of data. Embeddings are a type of
          representation of text that is used to represent the meaning of a
          given text. The embeddings are then used to generate new content that
          is similar to the primary accounts of Auschwitz.
        </li>
        <li className="lg:text-lg text-md list-disc">
          The list above, along with much of the project's code, was largely
          generated by AI.
        </li>
        <h1 className="lg:text-5xl text-3xl font-serif">
          The use of applied AI in history is intriguing and has the potential
          to revolutionize the field. Here's why:
        </h1>
        <li className="lg:text-lg text-md list-disc">
          AI can analyze large amounts of content in any language and provide
          summaries, answer questions, and generate new content. In The
          Auschwitz Project, this allowed us to analyze around 50 primary
          accounts accurately without reading many.
        </li>
        <li className="lg:text-lg text-md list-disc">
          AI can find and fix errors in text and translate documents. AI can
          also write code, teach students, generate images, automate tasks, and
          solve disputes
        </li>
        <li className="lg:text-lg text-md list-disc">
          AI can discover new information that is hidden in large amounts of
          data and find patterns. In scientific research, AI is being used to
          discover drugs.
        </li>
        <li>
          <Link href="/app">
            <button className="bg-gray-900 text-white rounded-md w-72 p-3">
              Speak with the Virtual Historian
            </button>
          </Link>
        </li>
        <h3 className="font-tight text-xl">
          The Auschwitz Project is a work in progress. We are constantly
          improving the project and adding new features. If you have any
          questions, comments, or concerns, please add an issue on{' '}
          <Link
            className="underline"
            href="https://github.com/LukeKosner/TAP/issues"
          >
            GitHub
          </Link>
          . For more information regarding acknowledgements, licencing, and the
          primary sources, go to the{' '}
          <Link
            href={'https://github.com/LukeKosner/TAP/blob/main/README.md'}
            className="underline"
          >
            README on GitHub
          </Link>
          . This project is not affiliated with the Auschwitz Memorial and
          Museum, the United States Holocaust Memorial Museum, or David Boder.
          The project is not intended to be used for research or academic
          purposes without fact-checking. Please be aware that the content of
          the AI generated prompts may be disturbing.
        </h3>
      </ul>
    </div>
  );
}
